#!/bin/bash

# NOTE: Lines starting with "#SBATCH" are valid SLURM commands or statements,
#       while those starting with "#" and "##SBATCH" are comments.  Uncomment
#       "##SBATCH" line means to remove one # and start with #SBATCH to be a
#       SLURM command or statement.


#SBATCH -J nete_slurm_job #Slurm job name

# Set the maximum runtime, uncomment if you need it
#SBATCH -t 24:00:00 #Maximum runtime of 24 hours

# Enable email notificaitons when job begins and ends, uncomment if you need it
#SBATCH --mail-user=walkerchow@pm.me #Update your email address
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

# Choose partition (queue) "gpu" or "gpu-share"
#SBATCH -p gpu-share

# To use 1 cpu core and 1 gpu device in 1 Node
#SBATCH -N 1 -n 3 --gres=gpu:3

# Setup runtime environment if necessary 
# or you can source ~/.bashrc or ~/.bash_profile 

# Go to the job submission directory and run your application 
cd /home/whychow/NETE

conda activate py38

# Execute applications in parallel 
# srun -n 2 --gres=gpu:1 myapp1 &    # Assign 2 CPU cores and 1 GPU device to run application "myapp1" 
# srun -n 1 --gres=gpu:1 python3 main.py --action=base_train --debug_interval=10 --base_model=with_progress --plot_progress==True --print=yo # Similarly, assign 1 CPU core and 1 GPU device to run application

srun -n 1 --gres=gpu:1 python3 main.py --action=base_train --debug_interval=10 --base_model=with_progress --plot_progress==True --c==0.1 --print=point1c &
srun -n 1 --gres=gpu:1 python3 main.py --action=base_train --debug_interval=10 --base_model=with_progress --plot_progress==True --c==10 --print=10c

# srun -n 1 --gres=gpu:1 python3 hello.py --print='test 0' &
# srun -n 1 --gres=gpu:1 python3 hello.py --print='test 1'
wait
